#install: gradle wrapper --gradle-version 5.1.1
dist: trusty
install: ./gradlew assemble
language: java
jdk:
  - oraclejdk8
  - openjdk8

before_script:
- chmod a+x gradlew

sccript: ./gradlew build 
notifications:
  slack: kalium-alkalio:TKKbLCQK8wW6HLPGfrGWyKUS
addons:
  sonarcloud:
    organization: "alkal-io" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner