/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.alkal.kalium.Kalium;
import io.alkal.kalium.tests.DummyKaliumQueueAdapter;
import io.alkal.kalium.tests.MyReactor;
import io.alkal.kalium.tests.Payment;
import org.junit.Test;
import org.mockito.Mockito;

public class LibraryTest {

    @Test public void testSomeLibraryMethod() {


        DummyKaliumQueueAdapter queueAdapter = new DummyKaliumQueueAdapter();

        Kalium kalium1 = Kalium.Builder()
                .setQueueAdapter(queueAdapter)
                .addReactor(MyReactor.class)
                .build();

        kalium1 = Mockito.spy(kalium1);
        MyReactor myReactor = Mockito.spy(kalium1.getReactorInstance(MyReactor.class));
        kalium1.start();

        Kalium kalium2 = Kalium.Builder()
                .setQueueAdapter(queueAdapter)
                .build();
        Mockito.spy(kalium2);
        kalium2.start();

        Payment payment = new Payment();

        kalium2.post(payment);

        Mockito.verify(myReactor).doSomething(Mockito.eq(payment));

    }


}
